### PR TITLE
Relax http-2 dependency

### PR DESCRIPTION
**Pull request by aried3r**
That way we're a bit more optimistic about changes and also don't fix people using that gem for other purposes. What do you think?

https://github.com/igrigorik/http-2/compare/v0.9.0...v0.9.1

### CODE REVIEW

**Comment by aried3r** [comment]
Not sure what happened with Ruby 2.2, seems like it timed out but also some tests failed. Are they flakey (see also #29)?

**Comment by ostinelli** [comment]
Unfortunately given we're still in the 0.x phase I do not want to relax dependencies. Most of the time, the gem version are very specifically linked.

**Comment by aried3r** [comment]
Ok! Would you be ok if I changed it to 0.9.1?
Alternatively we could allow 0.9.0 - 0.9.1 to not force people on one specific version since it seems to work with both.

**Comment by aried3r** [comment]
Hey, I changed it to allow both 0.9.0 and 0.9.1. Would that be ok for you?

**Comment by aried3r** [comment]
Closing, since 0.10.0 is out and you mentioned that the versions are usually closely coupled.

**Pull request closed without merging**
